# render.yaml  ← place in the repo root
#######################################

services:
  # 1️⃣  Web-service  (FastAPI)
  - name: booker-api          # final URL → https://booker-api.onrender.com
    type: web                 # <-- 'web_service', not just 'web'
    plan: free                # free instance; sleeps after 15 min
    runtime: python           # Render picks a Python image
    rootDir: .                # build at repo-root so requirements.txt is visible
    buildCommand: |
      pip install -r requirements.txt
      pip install -e .               # makes your `booker/` package importable
    startCommand: |
      uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATA_BASE_URL
        value: https://booker-chat-app.s3.us-east-2.amazonaws.com/
      - key: PYTHONUNBUFFERED        # nice to have for real-time logs
        value: "1"
      # OpenAI API Key - REQUIRED for the application to work
      - key: ragtagKey
        sync: false              # Prompt for value in Render Dashboard
      # Import all variables from your environment group
      - fromGroup: Booker Secrets    # Use exact name as it appears in Render dashboard
      # AWS credentials - will be prompted for during Blueprint creation
      - key: AWS_ACCESS_KEY_ID
        sync: false              # Prompt for value in Render Dashboard
      - key: AWS_SECRET_ACCESS_KEY
        sync: false              # Prompt for value in Render Dashboard
      - key: AWS_DEFAULT_REGION
        value: us-east-2         # Safe to hardcode region
      # Optional: if you're using S3 buckets
      - key: AWS_S3_BUCKET_NAME
        sync: false              # Prompt for value in Render Dashboard

  # 2️⃣  Static site  (React)
  - name: booker-ui            # final URL → https://booker-ui.onrender.com
    type: web                  # Static sites are type 'web'
    runtime: static            # Runtime is 'static' for static sites
    rootDir: ui                # where package.json lives
    buildCommand: |
      npm ci
      npm run build            # Vite creates ui/dist/
    staticPublishPath: dist

