# render.yaml  ← place in the repo root
#######################################

# 1️⃣  Web-service  (FastAPI)
services:
  - name: booker-api          # final URL → https://booker-api.onrender.com
    type: web                 # <-- ‘web_service’, not just ‘web’
    plan: free                # free instance; sleeps after 15 min
    runtime: python           # Render picks a Python image
    rootDir: .                # build at repo-root so requirements.txt is visible
    buildCommand: |
      pip install -r requirements.txt
      pip install -e .               # makes your `booker/` package importable
    startCommand: |
      uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATA_BASE_URL
        value: https://booker-chat-app.s3.us-east-2.amazonaws.com/
      - key: PYTHONUNBUFFERED        # nice to have for real-time logs
        value: "1"

# 2️⃣  Static site  (React)
staticPublishPath:
  - name: booker-ui            # final URL → https://booker-ui.onrender.com
    rootDir: ui                # where package.json lives
    buildCommand: |
      npm ci
      npm run build            # Vite creates ui/dist/
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL      # React knows where to talk
        value: https://booker-api.onrender.com
